---

- name: Provision an ansible target server with jenkins on java 8 and expose by nginx
  hosts: all
  gather_facts: true
  become: yes

  vars:
    jenkins_plugins:
      - ssh
    jenkins_plugin_timeout: 120
    nginx_use_ppa: true
    nginx_remove_default_vhost: true
    nginx_vhost_template: "{{ inventory_dir }}/templates/jenkins.j2"
    nginx_vhosts:
      - server_name: "jenkins.{{ inventory_hostname }}"
        listen: 80
        filename: "jenkins.{{ inventory_hostname }}"
  
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-8-jdk
    - role: geerlingguy.jenkins
    - role: geerlingguy.nginx    
